### ISSUE TITLE
Download link "Installer for Windows." is broken

### ISSUE THREAD

**Issue by malcolmshen** [ethereum/ethereum-org#283]
In https://www.ethereum.org/cli#install-on-windows, the link "[Installer for Windows](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/windows-installer.html)." is not available now.

**Comment by bobsummerwill** [comment]
That is correct.   Please could we strip out the Windows installer link for cpp-ethereum, @alexvandesande?   Ditto if there is a DMG link.   Both are gone.   Thanks!

**Comment by stianl** [comment]
5 months later. The link is still there and the page still does not exist.

Another link to **Download the [latest stable binary](https://build.ethdev.com/builds/Windows%20Go%20master%20branch/)** of the Geth client on the same page is also malfunctioning since builds are no longer published on builds.ethdev.com according to [this issue](https://github.com/ethereum/go-ethereum/issues/2884).

**Comment by ryanio** [comment]
This issue seems to be resolved, the broken link was removed here: https://github.com/ethereum/ethereum-org/commit/43d7fac358fcb61426ffa8560afce3bd492567d0#diff-51f2705891b1aa7f34ff84c6fc26ad3dL96

**Comment by bmann** [comment]
This can be closed.
