### ISSUE TITLE
Help. Private key file

### ISSUE THREAD

**Issue by BreakHeadz** [ethereum/ethereum-org#597]
Hello
How can I see the private key from my .json file of Basic Wallet on ethereum? 
Im not programmer and i can't use any scripts, maybe only if you tell me how to make it and what I need for it. 
I just forgot my password and I want to find out how to take out and see the private key in keystore file which I exported in folder for use the wallet and make transactions. because it seems no way to remind the password.. thanks.

**Comment by BreakHeadz** [comment]
![2017-05-28 20 54 45](https://cloud.githubusercontent.com/assets/28990443/26531335/bfa16630-43ef-11e7-8e79-d7eb182b108d.png)

**Comment by BreakHeadz** [comment]
everybody here?

**Comment by ottodevs** [comment]
This is not the place to ask questions like yours, please, better head to stackexchange, where it is answered like hundred times...
https://ethereum.stackexchange.com/questions/3720/how-do-i-get-the-raw-private-key-from-my-mist-keystore-file

Anyway the answer is NO, you cannot see the private key directly from your wallet, at least not directly, it is done on purpose because it would be a risk for the user.

I like to use this tool from infura, that just works, to obtain the raw private key from my json file + password: https://github.com/INFURA/tutorials
