### ISSUE TITLE
Update the Unicorn Token price

### ISSUE THREAD

**Issue by jdetychey** [ethereum/ethereum-org#648]
The unicorn token price in ETH has been left untouched since it was introduced.
Meanwhile the surge of the ETH token price to fiat is **critically threatening the growth of the unicorns in the wild**.
Looking at the transactions to the FoundationTipJar, only 6 new unicorns were born in the last 30 days and 12 over the last 60 days, compared to the hundreds of newborns when the contract was deployed...
IUCN Red List of Threatened Species classification is clear on this, **unicorns are Critically endangered and soon to be Extinct in the Wild**.

## Let's not let that happen and **lower the unicorn token price**.

_donation: jdetychey.eth (every wei will be redirected to unicorns)._

**Comment by alexvandesande** [comment]
Unicorns live forever. Unicorns are not cheap creatures, and should not be sold or put on Black Friday sale.

I'd rather close this despicable unicorn market altogether, and allow the existing unicorns to roam freely

**Comment by jdetychey** [comment]
You have a fair point here. But still, I have heard horrifying rumors you can't ignore of a hidden meat grinder contract and a black market for milled horn on tor. 
Can we fight market pressure and superstition over tradition medicine ([everybody knows fermented crab is the real deal](https://i.redditmedia.com/12LedBA6rPda3UiHa6d62LvWS5sDRyrYVTj3YqBv5_Q.jpg?w=700&s=247185dca471306f156d28253dcd2bd2) )?
Lives and rainbows are at stakes, is that the future we want for Serenity ?

**Comment by JosefJ** [comment]
How about building a reverse grinder, which would be giving out resurrected unicorns at lower price and sending the ether to the donation account?

**Comment by MidnightLightning** [comment]
I too [have noticed](https://www.reddit.com/r/ethereum/comments/6brd65/unicorn_price/) the lack of Unicorns dropping in price, and in the interim "me and my crazy cousin Lenny" [took matters into our own hands](https://steemit.com/ethereum/@midnight426/ethereum-beginners-guide-2-smart-contracts) creating an alternative.

As the donation page for the foundation indicates that their Unicorn tokens are "As a playful way to thank the donors", my opinion would be to have their price adjust over time to always stay within the approachable range for new donors (keeping the true value of the transaction in the "I donated to Ethereum's further development", and having the Unicorn token simply be a "proof I donated" badge, rather than "an asset I have worth 2 ETH"), as I believe that would encourage more people to donate, rather than keeping it as an elite status symbol only reachable by really large donors.

**Comment by jdetychey** [comment]
Fine EV, if you are closing this I am taking it to EIP. :moustache:
